#
# Joshua Henderson, joshua.henderson@microchip.com
# Copyright (C) 2014 Microchip Technology, Inc.  All rights reserved.
#
# Carsten Langgaard, carstenl@mips.com
# Copyright (C) 1999,2000 MIPS Technologies, Inc.  All rights reserved.
#
# Copyright (C) 2008 Wind River Systems, Inc.
#   written by Ralf Baechle <ralf@linux-mips.org>
#
obj-y				:= pic32-cmdline.o pic32-reset.o pic32-int.o pic32-gpio.o

