/*
 * Joshua Henderson, joshua.henderson@microchip.com
 * Copyright (C) 2014 Microchip Technology Inc.  All rights reserved.
 *
 *  This program is free software; you can distribute it and/or modify it
 *  under the terms of the GNU General Public License (Version 2) as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  for more details.
 */
#include <linux/init.h>
#include <linux/irq.h>
#include <linux/sched.h>
#include <linux/smp.h>
#include <linux/interrupt.h>
#include <linux/io.h>
#include <linux/kernel_stat.h>
#include <linux/kernel.h>
#include <linux/random.h>

#include <asm/traps.h>
#include <asm/irq_cpu.h>
#include <asm/irq_regs.h>
#include <asm/mips-boards/generic.h>
#include <asm/mach-pic32/pic32.h>
#include <asm/pic32.h>
#include <asm/mach-pic32/pic32int.h>

#define INTSTAT		0x0020
#define PIC32_REG(x)	((void __iomem *)(x))

asmlinkage void plat_irq_dispatch(void)
{
	int irq = __raw_readl(PIC32_REG(PIC32_BASE_INT + INTSTAT)) & 0xFF;

	if (irq >= 0)
		do_IRQ(MIPS_CPU_IRQ_BASE + irq);
	else
		spurious_interrupt();
}

#define DEFAULT_TICK_INT_PRI (1)
#define DEFAULT_INT_PRI (3)

#define DEFINE_INT(irq, pri) { irq, pri }

static struct pic32_irqmap pic_eicirqmap[] __initdata = {
	DEFINE_INT(CORE_TIMER_INTERRUPT, DEFAULT_TICK_INT_PRI),
	DEFINE_INT(CORE_SOFTWARE_INTERRUPT_0, DEFAULT_INT_PRI),
	DEFINE_INT(CORE_SOFTWARE_INTERRUPT_1, DEFAULT_INT_PRI),
	DEFINE_INT(EXTERNAL_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(TIMER1, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_1_ERROR, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_1, DEFAULT_INT_PRI),
	DEFINE_INT(OUTPUT_COMPARE_1, DEFAULT_INT_PRI),
	DEFINE_INT(EXTERNAL_INTERRUPT_1, DEFAULT_INT_PRI),
	DEFINE_INT(TIMER2, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_2_ERROR, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_2, DEFAULT_INT_PRI),
	DEFINE_INT(OUTPUT_COMPARE_2, DEFAULT_INT_PRI),
	DEFINE_INT(EXTERNAL_INTERRUPT_2, DEFAULT_INT_PRI),
	DEFINE_INT(TIMER3, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_3_ERROR, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_3, DEFAULT_INT_PRI),
	DEFINE_INT(OUTPUT_COMPARE_3, DEFAULT_INT_PRI),
	DEFINE_INT(EXTERNAL_INTERRUPT_3, DEFAULT_INT_PRI),
	DEFINE_INT(TIMER4, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_4_ERROR, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_4, DEFAULT_INT_PRI),
	DEFINE_INT(OUTPUT_COMPARE_4, DEFAULT_INT_PRI),
	DEFINE_INT(EXTERNAL_INTERRUPT_4, DEFAULT_INT_PRI),
	DEFINE_INT(TIMER5, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_5_ERROR, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_5, DEFAULT_INT_PRI),
	DEFINE_INT(OUTPUT_COMPARE_5, DEFAULT_INT_PRI),
	DEFINE_INT(TIMER6, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_6_ERROR, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_6, DEFAULT_INT_PRI),
	DEFINE_INT(OUTPUT_COMPARE_6, DEFAULT_INT_PRI),
	DEFINE_INT(TIMER7, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_7_ERROR, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_7, DEFAULT_INT_PRI),
	DEFINE_INT(OUTPUT_COMPARE_7, DEFAULT_INT_PRI),
	DEFINE_INT(TIMER8, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_8_ERROR, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_8, DEFAULT_INT_PRI),
	DEFINE_INT(OUTPUT_COMPARE_8, DEFAULT_INT_PRI),
	DEFINE_INT(TIMER9, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_9_ERROR, DEFAULT_INT_PRI),
	DEFINE_INT(INPUT_CAPTURE_9, DEFAULT_INT_PRI),
	DEFINE_INT(OUTPUT_COMPARE_9, DEFAULT_INT_PRI),
	/* ADC */
	DEFINE_INT(CORE_PERFORMANCE_COUNTER_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(CORE_FAST_DEBUG_CHANNEL_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(SYSTEM_BUS_PROTECTION_VIOLATION, DEFAULT_INT_PRI),
	DEFINE_INT(CRYPTO_ENGINE_EVENT, DEFAULT_INT_PRI),
	/* Reserved */
	DEFINE_INT(SPI1_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(SPI1_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(SPI1_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART1_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(UART1_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART1_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(I2C1_BUS_COLLISION_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(I2C1_SLAVE_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(I2C1_MASTER_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(PORTA_INPUT_CHANGE_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(PORTB_INPUT_CHANGE_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(PORTC_INPUT_CHANGE_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(PORTD_INPUT_CHANGE_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(PORTE_INPUT_CHANGE_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(PORTF_INPUT_CHANGE_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(PORTG_INPUT_CHANGE_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(PORTH_INPUT_CHANGE_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(PORTJ_INPUT_CHANGE_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(PORTK_INPUT_CHANGE_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(PARALLEL_MASTER_PORT, DEFAULT_INT_PRI),
	DEFINE_INT(PARALLEL_MASTER_PORT_ERROR, DEFAULT_INT_PRI),
	DEFINE_INT(COMPARATOR_1_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(COMPARATOR_2_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(USB_GENERAL_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(USB_DMA_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(DMA_CHANNEL_0, DEFAULT_INT_PRI),
	DEFINE_INT(DMA_CHANNEL_1, DEFAULT_INT_PRI),
	DEFINE_INT(DMA_CHANNEL_2, DEFAULT_INT_PRI),
	DEFINE_INT(DMA_CHANNEL_3, DEFAULT_INT_PRI),
	DEFINE_INT(DMA_CHANNEL_4, DEFAULT_INT_PRI),
	DEFINE_INT(DMA_CHANNEL_5, DEFAULT_INT_PRI),
	DEFINE_INT(DMA_CHANNEL_6, DEFAULT_INT_PRI),
	DEFINE_INT(DMA_CHANNEL_7, DEFAULT_INT_PRI),
	DEFINE_INT(SPI2_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(SPI2_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(SPI2_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART2_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(UART2_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART2_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(I2C2_BUS_COLLISION_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(I2C2_SLAVE_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(I2C2_MASTER_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(CONTROL_AREA_NETWORK_1, DEFAULT_INT_PRI),
	DEFINE_INT(CONTROL_AREA_NETWORK_2, DEFAULT_INT_PRI),
	DEFINE_INT(ETHERNET_INTERRUPT, DEFAULT_INT_PRI),
	DEFINE_INT(SPI3_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(SPI3_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(SPI3_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART3_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(UART3_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART3_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(I2C3_BUS_COLLISION_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(I2C3_SLAVE_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(I2C3_MASTER_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(SPI4_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(SPI4_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(SPI4_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(REAL_TIME_CLOCK, DEFAULT_INT_PRI),
	DEFINE_INT(FLASH_CONTROL_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(PREFETCH_MODULE_SEC_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(SQI1_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(UART4_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(UART4_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART4_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(I2C4_BUS_COLLISION_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(I2C4_SLAVE_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(I2C4_MASTER_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(SPI5_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(SPI5_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(SPI5_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART5_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(UART5_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART5_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(I2C5_BUS_COLLISION_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(I2C5_SLAVE_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(I2C5_MASTER_EVENT, DEFAULT_INT_PRI),
	DEFINE_INT(SPI6_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(SPI6_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(SPI6_TRANSFER_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART6_FAULT, DEFAULT_INT_PRI),
	DEFINE_INT(UART6_RECEIVE_DONE, DEFAULT_INT_PRI),
	DEFINE_INT(UART6_TRANSFER_DONE, DEFAULT_INT_PRI),
};

void __init arch_init_irq(void)
{
	init_pic32_irqs(MIPS_CPU_IRQ_BASE, pic_eicirqmap,
			ARRAY_SIZE(pic_eicirqmap));
}
