#
# Joshua Henderson, joshua.henderson@microchip.com
# Copyright (C) 2014 Microchip Technology, Inc.  All rights reserved.
#
obj-$(CONFIG_MACH_PIC32) += common/
obj-$(CONFIG_MIPS_PIC32MZ) += pic32mz_sk/
obj-$(CONFIG_MIPS_PIC32MZDA) += pic32mzda/
