#
# Joshua Henderson, joshua.henderson@microchip.com
# Copyright (C) 2014 Microchip Technology, Inc.  All rights reserved.
#
# Carsten Langgaard, carstenl@mips.com
# Copyright (C) 1999,2000 MIPS Technologies, Inc.  All rights reserved.
#
# Copyright (C) 2008 Wind River Systems, Inc.
#   written by Ralf Baechle <ralf@linux-mips.org>
#
obj-$(CONFIG_MACH_PIC32) += common/
obj-$(CONFIG_MIPS_PIC32MZ) += pic32mz_sk/
obj-$(CONFIG_MIPS_PIC32_EPLATFORM) += eplatform/
