/*
 * This header provides constants for the MICROCHIP PIC32 EVIC.
 */

#ifndef _DT_BINDINGS_INTERRUPT_CONTROLLER_MICROCHIP_EVIC_H
#define _DT_BINDINGS_INTERRUPT_CONTROLLER_MICROCHIP_EVIC_H

#include <dt-bindings/interrupt-controller/irq.h>

/* Hardware interrupt number */
#define CORE_TIMER_INTERRUPT 0
#define CORE_SOFTWARE_INTERRUPT_0 1
#define CORE_SOFTWARE_INTERRUPT_1 2
#define EXTERNAL_INTERRUPT_0 3
#define TIMER1 4
#define INPUT_CAPTURE_1_ERROR 5
#define INPUT_CAPTURE_1 6
#define OUTPUT_COMPARE_1 7
#define EXTERNAL_INTERRUPT_1 8
#define TIMER2 9
#define INPUT_CAPTURE_2_ERROR 10
#define INPUT_CAPTURE_2 11
#define OUTPUT_COMPARE_2 12
#define EXTERNAL_INTERRUPT_2 13
#define TIMER3 14
#define INPUT_CAPTURE_3_ERROR 15
#define INPUT_CAPTURE_3 16
#define OUTPUT_COMPARE_3 17
#define EXTERNAL_INTERRUPT_3 18
#define TIMER4 19
#define INPUT_CAPTURE_4_ERROR 20
#define INPUT_CAPTURE_4 21
#define OUTPUT_COMPARE_4 22
#define EXTERNAL_INTERRUPT_4 23
#define TIMER5 24
#define INPUT_CAPTURE_5_ERROR 25
#define INPUT_CAPTURE_5 26
#define OUTPUT_COMPARE_5 27
#define TIMER6 28
#define INPUT_CAPTURE_6_ERROR 29
#define INPUT_CAPTURE_6 30
#define OUTPUT_COMPARE_6 31
#define TIMER7 32
#define INPUT_CAPTURE_7_ERROR 33
#define INPUT_CAPTURE_7 34
#define OUTPUT_COMPARE_7 35
#define TIMER8 36
#define INPUT_CAPTURE_8_ERROR 37
#define INPUT_CAPTURE_8 38
#define OUTPUT_COMPARE_8 39
#define TIMER9 40
#define INPUT_CAPTURE_9_ERROR 41
#define INPUT_CAPTURE_9 42
#define OUTPUT_COMPARE_9 43
/* ADC */
#define CORE_PERFORMANCE_COUNTER_INTERRUPT 104
#define CORE_FAST_DEBUG_CHANNEL_INTERRUPT 105
#define SYSTEM_BUS_PROTECTION_VIOLATION 106
#define CRYPTO_ENGINE_EVENT 107
/* Reserved */
#define SPI1_FAULT 109
#define SPI1_RECEIVE_DONE 110
#define SPI1_TRANSFER_DONE 111
#define UART1_FAULT 112
#define UART1_RECEIVE_DONE 113
#define UART1_TRANSFER_DONE 114
#define I2C1_BUS_COLLISION_EVENT 115
#define I2C1_SLAVE_EVENT 116
#define I2C1_MASTER_EVENT 117
#define PORTA_INPUT_CHANGE_INTERRUPT 118
#define PORTB_INPUT_CHANGE_INTERRUPT 119
#define PORTC_INPUT_CHANGE_INTERRUPT 120
#define PORTD_INPUT_CHANGE_INTERRUPT 121
#define PORTE_INPUT_CHANGE_INTERRUPT 122
#define PORTF_INPUT_CHANGE_INTERRUPT 123
#define PORTG_INPUT_CHANGE_INTERRUPT 124
#define PORTH_INPUT_CHANGE_INTERRUPT 125
#define PORTJ_INPUT_CHANGE_INTERRUPT 126
#define PORTK_INPUT_CHANGE_INTERRUPT 127
#define PARALLEL_MASTER_PORT 128
#define PARALLEL_MASTER_PORT_ERROR 129
#define COMPARATOR_1_INTERRUPT 130
#define COMPARATOR_2_INTERRUPT 131
#define USB_GENERAL_EVENT 132
#define USB_DMA_EVENT 133
#define DMA_CHANNEL_0 134
#define DMA_CHANNEL_1 135
#define DMA_CHANNEL_2 136
#define DMA_CHANNEL_3 137
#define DMA_CHANNEL_4 138
#define DMA_CHANNEL_5 139
#define DMA_CHANNEL_6 140
#define DMA_CHANNEL_7 141
#define SPI2_FAULT 142
#define SPI2_RECEIVE_DONE 143
#define SPI2_TRANSFER_DONE 144
#define UART2_FAULT 145
#define UART2_RECEIVE_DONE 146
#define UART2_TRANSFER_DONE 147
#define I2C2_BUS_COLLISION_EVENT 148
#define I2C2_SLAVE_EVENT 149
#define I2C2_MASTER_EVENT 150
#define CONTROL_AREA_NETWORK_1 151
#define CONTROL_AREA_NETWORK_2 152
#define ETHERNET_INTERRUPT 153
#define SPI3_FAULT 154
#define SPI3_RECEIVE_DONE 155
#define SPI3_TRANSFER_DONE 156
#define UART3_FAULT 157
#define UART3_RECEIVE_DONE 158
#define UART3_TRANSFER_DONE 159
#define I2C3_BUS_COLLISION_EVENT 160
#define I2C3_SLAVE_EVENT 161
#define I2C3_MASTER_EVENT 162
#define SPI4_FAULT 163
#define SPI4_RECEIVE_DONE 164
#define SPI4_TRANSFER_DONE 165
#define REAL_TIME_CLOCK 166
#define FLASH_CONTROL_EVENT 167
#define PREFETCH_MODULE_SEC_EVENT 168
#define SQI1_EVENT 169
#define UART4_FAULT 170
#define UART4_RECEIVE_DONE 171
#define UART4_TRANSFER_DONE 172
#define I2C4_BUS_COLLISION_EVENT 173
#define I2C4_SLAVE_EVENT 174
#define I2C4_MASTER_EVENT 175
#define SPI5_FAULT 176
#define SPI5_RECEIVE_DONE 177
#define SPI5_TRANSFER_DONE 178
#define UART5_FAULT 179
#define UART5_RECEIVE_DONE 180
#define UART5_TRANSFER_DONE 181
#define I2C5_BUS_COLLISION_EVENT 182
#define I2C5_SLAVE_EVENT 183
#define I2C5_MASTER_EVENT 184
#define SPI6_FAULT 185
#define SPI6_RECEIVE_DONE 186
#define SPI6_TRANSFER_DONE 187
#define UART6_FAULT 188
#define UART6_RECEIVE_DONE 189
#define UART6_TRANSFER_DONE 190
/* microchip,eplatform-evic */
#define SDHC_EVENT 191

/* Interrupt priority bits */
#define PRI_0	0	/* Note:This priority disables the interrupt! */
#define PRI_1	1
#define PRI_2	2
#define PRI_3	3
#define PRI_4	4
#define PRI_5	5
#define PRI_6	6
#define PRI_7	7

/* Interrupt subpriority bits */
#define SUB_PRI_0	0
#define SUB_PRI_1	1
#define SUB_PRI_2	2
#define SUB_PRI_3	3

#define PRI_MASK	0x7	/* 3 bit priority mask */
#define SUBPRI_MASK	0x3	/* 2 bit subpriority mask */
#define INT_MASK	0x1F	/* 5 bit pri and subpri mask */
#define NR_EXT_IRQS	5	/* 5 external interrupts sources */

#define MICROCHIP_EVIC_MIN_PRIORITY 0
#define MICROCHIP_EVIC_MAX_PRIORITY INT_MASK

#define INT_PRI(pri, subpri)	\
	(((pri & PRI_MASK) << 2) | (subpri & SUBPRI_MASK))

#define DEFINE_INT(irq, pri) { irq, pri }

#define DEFAULT_INT_PRI INT_PRI(2, 0)

#endif /*_DT_BINDINGS_INTERRUPT_CONTROLLER_MICROCHIP_EVIC_H*/
